In [1]:
import numpy as np
from sklearn.neural_network import MLPClassifier

In [2]:
x = np.array([0,1,2,3,4])
y =  np.array([1,0,2,0,4])
print(x)
print(y)

[0 1 2 3 4]
[1 0 2 0 4]


In [3]:
x = x.reshape(-1,1)
x

array([[0],
       [1],
       [2],
       [3],
       [4]])

Construir y entrenar el model

In [24]:
model = MLPClassifier(activation="logistic",alpha=0.001, solver="lbfgs")
model.fit(x,y)
model.get_params()

{'activation': 'logistic',
 'alpha': 0.001,
 'batch_size': 'auto',
 'beta_1': 0.9,
 'beta_2': 0.999,
 'early_stopping': False,
 'epsilon': 1e-08,
 'hidden_layer_sizes': (100,),
 'learning_rate': 'constant',
 'learning_rate_init': 0.001,
 'max_fun': 15000,
 'max_iter': 200,
 'momentum': 0.9,
 'n_iter_no_change': 10,
 'nesterovs_momentum': True,
 'power_t': 0.5,
 'random_state': None,
 'shuffle': True,
 'solver': 'lbfgs',
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': False,
 'warm_start': False}

Predecir modelo y comparar con original

In [25]:
y_pred = model.predict(x)
print(y)
print(y_pred)

[1 0 2 0 4]
[1 0 2 0 4]


Predicir con el model

In [26]:
to_predict = [[10],[4],[2]]
model.predict(to_predict)

array([4, 4, 2])